services:
  db:
    image: postgres:18-alpine3.22
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prservice

  migrator:
    image: migrate/migrate
    command:
      ["-path", "/migrations", "-database", "postgresql://postgres:postgres@db:5432/prservice?sslmode=disable", "up"]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_started

    restart: "on-failure"

  prservice:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/prservice?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      migrator:
        condition: service_completed_successfully
volumes:
  db-data: